function c = config(varargin)
%CONFIG 任务10风场模型库配置：在任务7/8全部口径之上新增可选风场模型。
% 继承任务7实际约束(转弯半径50-150m物理化 / 通信时延0-0.5s(任务10放宽下限:
% 0=无时延对照口径, 需求口径0.1-0.5) / 加速度限幅
% 2 m/s^2 / 开环固定基线)与任务8曲线标定(DJI Mavic Pro参考: 悬停103.7W、
% 谷底V*=6.3m/s、P(20)=134.5W; curveCase=谷底/悬停∈{0.95,0.90,0.85};
% 内部归一化单位, 面板按pHover换算瓦特)。
% 任务10新增风场参数(wind_field.m 七种模型):
%   windKind    'const'|'sin'(默认,任务4/5/8原口径)|'square'|'triangle'|
%               'turb'|'composite'(最贴近实际,推荐面板默认)|'sector'
%   squareEdge  方波软边陡度k(默认4; 1≈正弦, k→∞纯方波, 纯方波不物理)
%   turbStd     composite中湍流平稳标准差(默认0.3 m/s)
%   turbTheta   OU湍流速率参数(默认0.2 → 相关时间5 s)
% 速度语义(用户口径, 与对象物理一致): 空速=地速+风速(矢量), 功率由空速决定
% (空速-功率标定曲线不随风移动), 地速-功率曲线随风平移, 仪表盘显示地速。
% 对象侧升级不改控制器因果接口(AGENTS.md红线2): 算法仍只调 plant.q(v,tag)。
c=struct('lower',0,'upper',20,'optimum0',6.3,...
    'pHover',103.7,'p20',134.5,'curveCase',0.90,...
    'rippleA1',0.022,'rippleL1',6.0,'rippleF1',pi,...
    'rippleA2',0.012,'rippleL2',2.0,'rippleF2',pi,...
    'noiseSigma',0.01,'impulse',false,'impulseRate',0.03,'impulseSize',0.10,...
    'tEval',1.0,'duration',400,'T',400,'tailSteps',60,'seed',1,...
    'tol',0.02,'maxSearchEval',60,'eps',0.4,...
    'initialSpeed',6.3,...   % 任务7口径: 以名义巡航速度开始任务窗(爬升段不在评价窗内)
    'turnRadius',100,'latencySec',0.3,'aMax',2.0,'subSteps',10,'openLoopV',6.3,...
    'shiftTime',120,'jumpUpDx',2.7,'jumpDownDx',-2.3,'dyOffset',0.05,...
    'rampStart',60,'rampEnd',180,'rampDx',1.7,...
    't1ProbeDelta',0.5,'t1ProbePeriod',10,'t1SlopeThresh',0.002,...
    't1SlopeRelease',0.0005,'t1Span0',3.0,'t1Grow',2.0,'t1Retry',2,...
    'probePeriod',12,'probeDelta',3.0,'probeRepeats',2,...
    'slopeThresh',0.01,'ghatThresh',0.012,'relocalMax',3,...
    'escA',0.5,'escOmega',0.5,'escGain',8,'escLpOmega',0.5,'escWindow',7,...
    'spsaGain',70,'spsaCk',1.5,'spsaEwma',0.2,'spsaStepMax',0.8,'spsaPeriod',8,...
    'bayesInitN',7,'bayesWindow',36,'bayesRefit',6,'bayesKappa',2.0,'bayesPeriod',2,'bayesRadius',9.9,'bayesTau',0.004,'bayesEvery',7,'bayesRad',2.0,...
    'qnD',1.5,'qnS',0.25,'qnPairs',2,'qnHold',2,'qnEwmaG',0.35,'qnEwmaB',0.15,...
    'qnStepMax',0.4,'qnB0',0.006,'qnBmin',1e-3,'qnBmax',0.2,'qnSecMin',0.25,...
    'qnWideGain',60,'qnCalmThr',0.0015,'qnWideEvery',20,'qnWideThr',0.004,...
    'gtDither',0.3,'gtGain',30,'gtEwma',0.25,...
    'estDither',0.4,'estQa',0.05,'estRmis',0.02,'estStepClamp',0.4,...
    'windAmp',2.0,'windOmega',0.08,'windBias',3.0,...
    'windAmpY',0.0,'windOmegaY',0.13,'windBiasY',0.0,...
    'windDirDeg',0,...
    'windKind','sin','squareEdge',4.0,'turbStd',0.3,'turbTheta',0.2,...
    'energyAccounting',true);
if ~isempty(varargin) && isstruct(varargin{1})   % 支持以struct为基底覆盖
    base=varargin{1}; fn=fieldnames(base);
    for kb=1:numel(fn), c.(fn{kb})=base.(fn{kb}); end
    varargin(1)=[];
end
assert(mod(numel(varargin),2)==0,'w10:Config','Use name/value pairs.');
for k=1:2:numel(varargin)
    key=char(varargin{k}); assert(isfield(c,key),'w10:Config','Unknown setting: %s',key);
    c.(key)=varargin{k+1};
end
assert(islogical(c.energyAccounting) && isscalar(c.energyAccounting),...
    'w10:Config','energyAccounting must be logical.');
assert(islogical(c.impulse) && isscalar(c.impulse),'w10:Config','impulse must be logical.');
positive={'tEval','duration','T','tailSteps','tol','maxSearchEval','eps','initialSpeed',...
    'turnRadius','latencySec','aMax','subSteps','openLoopV',...
    'shiftTime','dyOffset','rampStart','rampEnd','rampDx',...
    'rippleA1','rippleL1','rippleA2','rippleL2','noiseSigma','impulseRate','impulseSize',...
    't1ProbeDelta','t1ProbePeriod','t1SlopeThresh','t1SlopeRelease','t1Span0','t1Grow','t1Retry',...
    'probePeriod','probeDelta','probeRepeats',...
    'slopeThresh','relocalMax','ghatThresh','escA','escOmega','escGain','escLpOmega','escWindow',...
    'seed','windAmp','windBias','windAmpY','windBiasY',...
    'spsaGain','spsaCk','spsaEwma','spsaStepMax','spsaPeriod',...
    'bayesInitN','bayesWindow','bayesRefit','bayesKappa','bayesPeriod','bayesRadius','bayesTau',...
    'bayesEvery','bayesRad',...
    'qnD','qnS','qnPairs','qnHold','qnEwmaG','qnEwmaB','qnStepMax',...
    'qnB0','qnBmin','qnBmax','qnSecMin','qnWideGain','qnCalmThr','qnWideEvery','qnWideThr',...
    'gtDither','gtGain','gtEwma','estDither','estQa','estRmis','estStepClamp'};
for k=1:numel(positive), validateattributes(c.(positive{k}),{'double'},...
    {'scalar','real','finite','nonnegative'}); end
signed={'jumpUpDx','jumpDownDx','windDirDeg','windOmega','windOmegaY'};
for k=1:numel(signed), validateattributes(c.(signed{k}),{'double'},{'scalar','real','finite'}); end
assert(ischar(c.windKind) && any(strcmp(c.windKind,...
    {'const','sin','square','triangle','turb','composite','sector'})),...
    'w10:Config','windKind must be const/sin/square/triangle/turb/composite/sector.');
assert(c.squareEdge>=0.5,'w10:Config','squareEdge must be >=0.5 (1≈正弦, 越大方波越陡).');
assert(c.turbStd>=0 && c.turbTheta>0,'w10:Config','turbStd must be >=0 (0=无湍流), turbTheta>0.');
assert(any(abs(c.curveCase-[0.95 0.90 0.85])<1e-12),'w10:Config',...
    'curveCase must be 0.95 / 0.90 / 0.85.');
assert(c.lower>=0 && c.upper>c.lower && c.optimum0>=c.lower && c.optimum0<=c.upper,...
    'w10:Config','Invalid bounds/optimum.');
% ---- 三次光滑标定曲线系数(涟漪锚点补偿: P(0)=1 与 P(V*)=curveCase 精确成立) ----
rip0=c.rippleA1*cos(2*pi*(0-c.optimum0)/c.rippleL1+c.rippleF1)...
    +c.rippleA2*cos(2*pi*(0-c.optimum0)/c.rippleL2+c.rippleF2);
s0=1-rip0;
sV=c.curveCase+c.rippleA1+c.rippleA2;
s20=c.p20/c.pHover;
V=c.optimum0;
M=[0 0 0 1; V^3 V^2 V 1; 3*V^2 2*V 1 0; 20^3 20^2 20 1];
c.curveCoef=(M\[s0;sV;0;s20]).';
assert(c.initialSpeed>=c.lower && c.initialSpeed<=c.upper,'w10:Config','Initial speed outside bounds.');
assert(c.openLoopV>=c.lower && c.openLoopV<=c.upper,'w10:Config','openLoopV outside bounds.');
% ---- 任务7实际约束的有效范围 ----
assert(c.turnRadius>=30 && c.turnRadius<=600,'w10:Config',...
    'turnRadius must be in [30,600] m (研究口径50-150; 500仅作任务6旧参考).');
assert(c.latencySec>=0 && c.latencySec<=0.5,'w10:Config',...
    'latencySec must be in [0,0.5] s (0=无时延对照口径; 需求口径0.1-0.5).');
assert(c.aMax>=0.5 && c.aMax<=5,'w10:Config','aMax must be in [0.5,5] m/s^2 (需求=2).');
assert(c.subSteps>=10 && mod(c.subSteps,1)==0,'w10:Config',...
    'subSteps must be integer >=10 (0.1 s子步分辨率, 匹配最小时延).');
assert(c.duration>c.tailSteps,'w10:Config','duration too short.');
assert(c.t1SlopeRelease<c.t1SlopeThresh,'w10:Config','t1SlopeRelease<t1SlopeThresh required.');
assert(c.t1ProbeDelta>0 && 2*c.t1ProbeDelta<c.upper-c.lower,'w10:Config','Invalid t1ProbeDelta.');
assert(c.bayesInitN>=3 && c.bayesWindow>=c.bayesInitN && c.bayesRefit>=1,...
    'w10:Config','Invalid bayes surrogate settings.');
assert(c.spsaCk>0 && 2*c.spsaCk<c.upper-c.lower,'w10:Config','Invalid spsa probe settings.');
assert(c.spsaPeriod>=2 && mod(c.spsaPeriod,1)==0,'w10:Config','spsaPeriod must be integer >=2.');
assert(c.bayesPeriod>=1 && mod(c.bayesPeriod,1)==0,'w10:Config','bayesPeriod must be integer >=1.');
assert(c.qnD>0 && 2*c.qnD<c.upper-c.lower && c.qnWideEvery>=4 && mod(c.qnWideEvery,1)==0,...
    'w10:Config','Invalid qnewton wide-monitor settings.');
assert(c.qnPairs>=1 && c.qnHold>=0 && c.qnS>0 && 2*c.qnS<c.upper-c.lower,...
    'w10:Config','Invalid qnewton cycle settings.');
assert(c.qnBmin<c.qnB0 && c.qnB0<c.qnBmax && c.qnSecMin>0,...
    'w10:Config','Invalid qnewton curvature settings.');
end
